<a href="https://colab.research.google.com/github/aycarl/Python-Tests/blob/master/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Calculating Singular Value Decomposition in Python


---


1. Import numpy

In [0]:
import numpy as np


2. upload data file from  local drive

3. save imported data into variable (in this case "realestate")

In [0]:
from google.colab import files
realestateFile = files.upload()

realestate = np.loadtxt("RealEstate.txt", usecols=range(4))

Saving RealEstate.txt to RealEstate (1).txt


In [0]:
print(realestate)

[[ 68900.   5960.  44967.   1873.]
 [ 48500.   9000.  27860.    928.]
 [ 55500.   9500.  31439.   1126.]
 [ 62000.  10000.  39592.   1265.]
 [116500.  18000.  72827.   2214.]
 [ 45000.   8500.  27317.    912.]
 [ 38000.   8000.  29856.    899.]
 [ 83000.  23000.  47752.   1803.]
 [ 59000.   8100.  39117.   1204.]
 [ 47500.   9000.  29349.   1725.]
 [ 40500.   7300.  40166.   1080.]
 [ 40000.   8000.  31679.   1529.]
 [ 97000.  20000.  58510.   2455.]
 [ 45500.   8000.  23454.   1151.]
 [ 40900.   8000.  20897.   1173.]
 [ 80000.  10500.  56248.   1960.]
 [ 56000.   4000.  20859.   1344.]
 [ 37000.   4500.  22610.    988.]
 [ 50000.   3400.  35948.   1076.]
 [ 22400.   1500.   5779.    962.]]


4. Calculate SVD

In [0]:
u, s, v = np.linalg.svd(realestate)
print("U=", u)
print("S=", s)
print("v=", v)

U= [[-2.54043074e-01  9.34806191e-02 -3.72662939e-01  1.87216219e-01
  -2.46746921e-01 -6.17023245e-02 -1.03316681e-01  7.77356745e-02
  -1.89253473e-01 -2.71794373e-01 -2.26946025e-01 -2.78470401e-01
  -2.14205113e-01 -1.16090157e-01 -1.17338357e-01 -3.77103327e-01
  -2.42555451e-01 -1.86312206e-01 -2.90430914e-01 -1.98536480e-01]
 [-1.74711334e-01 -9.95886971e-02  5.90176407e-02 -1.62719390e-01
  -1.29566823e-01 -1.43302170e-01 -1.72281240e-01 -7.15341470e-01
   7.41801870e-04 -1.09966304e-01 -1.08005843e-01 -1.21816746e-01
  -3.86104596e-01 -9.01773561e-02 -1.23841990e-01  4.68410744e-02
   2.60778256e-01  5.21991280e-02  2.18895169e-01  1.37468319e-01]
 [-1.98869752e-01 -1.26190756e-01  1.19400054e-02 -1.35991248e-01
  -1.32612264e-01 -6.50389592e-02  1.99575989e-01 -1.54973980e-01
   1.16826943e-02  1.34467403e-02  5.08073810e-01  2.65003199e-01
  -1.01491763e-01 -1.96751328e-01 -1.66569475e-01  1.52806013e-01
  -5.67220335e-01 -4.43680812e-02  9.04351487e-02 -2.82048346e-01]
 [-2